CREATE TABLE IF NOT EXISTS pets
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type VARCHAR(255)                            NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    age  INTEGER                                 NOT NULL,
    CONSTRAINT pk_pet PRIMARY KEY (id),
    CONSTRAINT UQ_PET_NAME UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS owners
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                          NOT NULL,
    CONSTRAINT pk_owner PRIMARY KEY (id),
    CONSTRAINT UQ_OWNER_NAME UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS pets_for_owner
(
    id_owner BIGINT,
    id_pet  BIGINT,
    PRIMARY KEY (id_owner, id_pet),
    CONSTRAINT fk_id_owner FOREIGN KEY (id_owner) REFERENCES owners (id),
    CONSTRAINT fk_id_pet FOREIGN KEY (id_pet) REFERENCES pets (id)
);


